import {
  Activity,
  AirVent,
  AlarmClock,
  Ambulance,
  Anchor,
  Angry,
  Apple,
  Archive,
  ArrowDownToLine,
  ArrowUpFromLine,
  Award,
  Axe,
  Baby,
  Backpack,
  BadgeDollarSign,
  BaggageClaim,
  Banana,
  Banknote,
  BarChart,
  BarChart2,
  BarChart3,
  Bath,
  Battery,
  Bed,
  Beer,
  Bell,
  Bike,
  Bitcoin,
  Bluetooth,
  Book,
  BookOpen,
  Bookmark,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  BusFront,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  Candy,
  Car,
  Carrot,
  Cat,
  ChefHat,
  Cherry,
  Citrus,
  CircleDollarSign,
  Clipboard,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  Cloudy,
  Code,
  Coffee,
  Coins,
  Combine,
  Cone,
  Construction,
  Container,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Database,
  Dessert,
  Diamond,
  DollarSign,
  Dog,
  Drill,
  Droplet,
  Dumbbell,
  Ear,
  Earth,
  Egg,
  Euro,
  Eye,
  Factory,
  Fence,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flashlight,
  FlaskConical,
  Flower,
  Flower2,
  Folder,
  Fuel,
  Gamepad,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Hammer,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  Heater,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  IceCream,
  IndianRupee,
  JapaneseYen,
  Key,
  Lamp,
  LampDesk,
  Landmark,
  Laptop,
  Laugh,
  Leaf,
  Lightbulb,
  LineChart,
  Link,
  Lock,
  Luggage,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageSquare,
  Mic,
  Microscope,
  Milk,
  Monitor,
  Moon,
  Palette,
  Mountain,
  Music,
  Navigation,
  Network,
  Newspaper,
  Paintbrush,
  PaintRoller,
  PanelTop,
  Package,
  PartyPopper,
  PawPrint,
  Pencil,
  Percent,
  Phone,
  PieChart,
  PiggyBank,
  Pill,
  Pin,
  Pipette,
  Pizza,
  Plane,
  Plug,
  Plus,
  Pocket,
  Presentation,
  Printer,
  Radio,
  Receipt,
  ReceiptText,
  Refrigerator,
  Repeat,
  Rocket,
  Router,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Motorbike,
  Satellite,
  Scale,
  Scissors,
  School,
  Server,
  Settings,
  Shell,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Tablet,
  Tag,
  Tags,
  Target,
  Tent,
  Thermometer,
  Timer,
  Tornado,
  Tractor,
  Train,
  TramFront,
  Trash,
  TrendingDown,
  TrendingUp,
  Trees,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Vault,
  Wallet,
  WashingMachine,
  Watch,
  Waves,
  Webhook,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide";

export const iconOptions = [
  // Finanças & Investimentos
  { id: "wallet", label: "Carteira", icon: Wallet },
  { id: "credit-card", label: "Cartão de crédito", icon: CreditCard },
  { id: "banknote", label: "Dinheiro", icon: Banknote },
  { id: "coins", label: "Moedas", icon: Coins },
  { id: "dollar-sign", label: "Dólar", icon: DollarSign },
  { id: "circle-dollar-sign", label: "Salário", icon: CircleDollarSign },
  { id: "badge-dollar-sign", label: "Bônus", icon: BadgeDollarSign },
  { id: "euro", label: "Euro", icon: Euro },
  { id: "indian-rupee", label: "Rúpia", icon: IndianRupee },
  { id: "japanese-yen", label: "Iene", icon: JapaneseYen },
  { id: "bitcoin", label: "Bitcoin", icon: Bitcoin },
  { id: "receipt", label: "Recibo", icon: Receipt },
  { id: "receipt-text", label: "Extrato", icon: ReceiptText },
  { id: "piggy-bank", label: "Poupança", icon: PiggyBank },
  { id: "vault", label: "Cofre", icon: Vault },
  { id: "landmark", label: "Banco", icon: Landmark },
  { id: "trending-up", label: "Crescimento", icon: TrendingUp },
  { id: "trending-down", label: "Queda", icon: TrendingDown },
  { id: "bar-chart", label: "Gráfico de Barras", icon: BarChart },
  { id: "bar-chart-2", label: "Gráfico", icon: BarChart2 },
  { id: "bar-chart-3", label: "Estatísticas", icon: BarChart3 },
  { id: "line-chart", label: "Gráfico Linear", icon: LineChart },
  { id: "pie-chart", label: "Gráfico Pizza", icon: PieChart },
  { id: "percent", label: "Porcentagem", icon: Percent },
  { id: "calculator", label: "Calculadora", icon: Calculator },
  { id: "scale", label: "Balanço", icon: Scale },
  { id: "tag", label: "Tag", icon: Tag },
  { id: "tags", label: "Tags", icon: Tags },
  { id: "target", label: "Meta Financeira", icon: Target },
  { id: "diamond", label: "Investimento Premium", icon: Diamond },
  { id: "gem", label: "Joia / Luxo", icon: Gem },

  // Receitas / Entradas
  { id: "arrow-down-to-line", label: "Recebimento", icon: ArrowDownToLine },
  { id: "arrow-up-from-line", label: "Pagamento", icon: ArrowUpFromLine },
  { id: "handshake", label: "Contrato", icon: Handshake },
  { id: "repeat", label: "Recorrente", icon: Repeat },
  { id: "award", label: "Prêmio", icon: Award },
  { id: "gift", label: "Presente", icon: Gift },

  // Compras & Varejo
  { id: "shopping-cart", label: "Mercado", icon: ShoppingCart },
  { id: "shopping-bag", label: "Compras", icon: ShoppingBag },
  { id: "shopping-basket", label: "Cesta", icon: ShoppingBasket },
  { id: "store", label: "Loja", icon: Store },
  { id: "package", label: "Pacote", icon: Package },
  { id: "container", label: "Contêiner", icon: Container },

  // Casa & Móveis
  { id: "home", label: "Casa", icon: Home },
  { id: "building", label: "Prédio", icon: Building },
  { id: "building-2", label: "Condomínio", icon: Building2 },
  { id: "sofa", label: "Móveis", icon: Sofa },
  { id: "bed", label: "Cama", icon: Bed },
  { id: "bath", label: "Banheiro", icon: Bath },
  { id: "lamp", label: "Iluminação", icon: Lamp },
  { id: "lamp-desk", label: "Luminária", icon: LampDesk },
  { id: "lightbulb", label: "Energia", icon: Lightbulb },
  { id: "plug", label: "Eletricidade", icon: Plug },
  { id: "zap", label: "Energia Elétrica", icon: Zap },
  { id: "air-vent", label: "Ar Condicionado", icon: AirVent },
  { id: "heater", label: "Aquecedor", icon: Heater },
  { id: "refrigerator", label: "Geladeira", icon: Refrigerator },
  { id: "washing-machine", label: "Lavanderia", icon: WashingMachine },
  { id: "wrench", label: "Manutenção", icon: Wrench },
  { id: "hammer", label: "Reforma", icon: Hammer },
  { id: "drill", label: "Ferramentas", icon: Drill },
  { id: "axe", label: "Construção Pesada", icon: Axe },
  { id: "shovel", label: "Jardinagem", icon: Shovel },
  { id: "paintbrush", label: "Pintura", icon: Paintbrush },
  { id: "paint-roller", label: "Pintor", icon: PaintRoller },
  { id: "construction", label: "Obras", icon: Construction },
  { id: "fence", label: "Cerca", icon: Fence },
  { id: "key", label: "Aluguel", icon: Key },
  { id: "lock", label: "Segurança", icon: Lock },
  { id: "scissors", label: "Serviços", icon: Scissors },
  { id: "trash", label: "Lixo", icon: Trash },
  { id: "droplet", label: "Água", icon: Droplet },
  { id: "flame", label: "Gás", icon: Flame },

  // Alimentação & Bebidas
  { id: "utensils", label: "Alimentação", icon: Utensils },
  { id: "utensils-crossed", label: "Restaurante", icon: UtensilsCrossed },
  { id: "chef-hat", label: "Cozinha", icon: ChefHat },
  { id: "coffee", label: "Café", icon: Coffee },
  { id: "pizza", label: "Pizza", icon: Pizza },
  { id: "sandwich", label: "Lanche", icon: Sandwich },
  { id: "cake", label: "Bolo", icon: Cake },
  { id: "cookie", label: "Biscoito", icon: Cookie },
  { id: "croissant", label: "Croissant", icon: Croissant },
  { id: "ice-cream", label: "Sorvete", icon: IceCream },
  { id: "candy", label: "Doce", icon: Candy },
  { id: "dessert", label: "Sobremesa", icon: Dessert },
  { id: "apple", label: "Frutas", icon: Apple },
  { id: "banana", label: "Banana", icon: Banana },
  { id: "cherry", label: "Cereja", icon: Cherry },
  { id: "citrus", label: "Cítricos", icon: Citrus },
  { id: "grape", label: "Uva", icon: Grape },
  { id: "carrot", label: "Verduras", icon: Carrot },
  { id: "salad", label: "Salada", icon: Salad },
  { id: "soup", label: "Sopa", icon: Soup },
  { id: "fish", label: "Peixe", icon: Fish },
  { id: "egg", label: "Ovo", icon: Egg },
  { id: "milk", label: "Leite", icon: Milk },
  { id: "wheat", label: "Trigo", icon: Wheat },
  { id: "beer", label: "Cerveja", icon: Beer },
  { id: "wine", label: "Vinho", icon: Wine },

  // Transporte
  { id: "car", label: "Carro", icon: Car },
  { id: "bus", label: "Ônibus", icon: Bus },
  { id: "bus-front", label: "Transporte Público", icon: BusFront },
  { id: "tram-front", label: "Bonde", icon: TramFront },
  { id: "train", label: "Trem", icon: Train },
  { id: "bike", label: "Bicicleta", icon: Bike },
  { id: "motorbike", label: "Moto", icon: Motorbike },
  { id: "plane", label: "Avião", icon: Plane },
  { id: "rocket", label: "Foguete", icon: Rocket },
  { id: "ship", label: "Navio", icon: Ship },
  { id: "sailboat", label: "Barco à Vela", icon: Sailboat },
  { id: "anchor", label: "Âncora", icon: Anchor },
  { id: "truck", label: "Frete", icon: Truck },
  { id: "tractor", label: "Trator", icon: Tractor },
  { id: "ambulance", label: "Ambulância", icon: Ambulance },
  { id: "fuel", label: "Combustível", icon: Fuel },
  { id: "gauge", label: "Velocímetro", icon: Gauge },
  { id: "map", label: "Mapa", icon: Map },
  { id: "map-pin", label: "Localização", icon: MapPin },
  { id: "navigation", label: "Navegação", icon: Navigation },

  // Saúde & Bem-estar
  { id: "heart", label: "Coração", icon: Heart },
  { id: "heart-pulse", label: "Saúde", icon: HeartPulse },
  { id: "activity", label: "Atividade", icon: Activity },
  { id: "stethoscope", label: "Médico", icon: Stethoscope },
  { id: "hospital", label: "Hospital", icon: Hospital },
  { id: "pill", label: "Remédio", icon: Pill },
  { id: "syringe", label: "Vacina", icon: Syringe },
  { id: "thermometer", label: "Termômetro", icon: Thermometer },
  { id: "dumbbell", label: "Academia", icon: Dumbbell },
  { id: "eye", label: "Oftalmologista", icon: Eye },
  { id: "ear", label: "Otorrino", icon: Ear },
  { id: "smile", label: "Dentista", icon: Smile },

  // Trabalho & Negócios
  { id: "briefcase", label: "Trabalho", icon: Briefcase },
  { id: "briefcase-business", label: "Negócios", icon: BriefcaseBusiness },
  { id: "laptop", label: "Computador", icon: Laptop },
  { id: "monitor", label: "Monitor", icon: Monitor },
  { id: "printer", label: "Impressora", icon: Printer },
  { id: "phone", label: "Telefone", icon: Phone },
  { id: "mail", label: "E-mail", icon: Mail },
  { id: "message-square", label: "Mensagem", icon: MessageSquare },
  { id: "clipboard", label: "Relatório", icon: Clipboard },
  { id: "file-text", label: "Documento", icon: FileText },
  { id: "folder", label: "Pasta", icon: Folder },
  { id: "archive", label: "Arquivo", icon: Archive },
  { id: "calendar", label: "Agenda", icon: Calendar },
  { id: "calendar-check", label: "Agendado", icon: CalendarCheck },
  { id: "calendar-clock", label: "Prazo", icon: CalendarClock },
  { id: "clock", label: "Horas Extras", icon: Clock },
  { id: "alarm-clock", label: "Alarme", icon: AlarmClock },
  { id: "timer", label: "Cronômetro", icon: Timer },
  { id: "hourglass", label: "Ampulheta", icon: Hourglass },
  { id: "presentation", label: "Apresentação", icon: Presentation },
  { id: "network", label: "Rede", icon: Network },
  { id: "factory", label: "Fábrica", icon: Factory },
  { id: "combine", label: "Indústria", icon: Combine },

  // Educação
  { id: "book", label: "Livro", icon: Book },
  { id: "book-open", label: "Leitura", icon: BookOpen },
  { id: "graduation-cap", label: "Educação", icon: GraduationCap },
  { id: "school", label: "Escola", icon: School },
  { id: "microscope", label: "Ciência", icon: Microscope },
  { id: "flask-conical", label: "Química", icon: FlaskConical },
  { id: "pencil", label: "Lápis", icon: Pencil },
  { id: "ruler", label: "Régua", icon: Ruler },
  { id: "newspaper", label: "Jornal", icon: Newspaper },

  // Lazer & Entretenimento
  { id: "music", label: "Música", icon: Music },
  { id: "headphones", label: "Fones", icon: Headphones },
  { id: "speaker", label: "Alto-falante", icon: Speaker },
  { id: "mic", label: "Microfone", icon: Mic },
  { id: "radio", label: "Rádio", icon: Radio },
  { id: "tv", label: "TV / Streaming", icon: Tv },
  { id: "film", label: "Cinema", icon: Film },
  { id: "camera", label: "Fotografia", icon: Camera },
  { id: "gamepad", label: "Videogame", icon: Gamepad },
  { id: "gamepad-2", label: "Games", icon: Gamepad2 },
  { id: "party-popper", label: "Festa", icon: PartyPopper },
  { id: "star", label: "Destaque", icon: Star },
  { id: "trophy", label: "Conquista", icon: Trophy },
  { id: "medal", label: "Medalha", icon: Medal },
  { id: "palette", label: "Arte", icon: Palette },
  { id: "laugh", label: "Diversão", icon: Laugh },
  { id: "sparkles", label: "Especial", icon: Sparkles },

  // Tecnologia & Internet
  { id: "smartphone", label: "Celular", icon: Smartphone },
  { id: "tablet", label: "Tablet", icon: Tablet },
  { id: "cpu", label: "Hardware", icon: Cpu },
  { id: "hard-drive", label: "Armazenamento", icon: HardDrive },
  { id: "database", label: "Banco de Dados", icon: Database },
  { id: "server", label: "Servidor", icon: Server },
  { id: "wifi", label: "Internet", icon: Wifi },
  { id: "router", label: "Roteador", icon: Router },
  { id: "bluetooth", label: "Bluetooth", icon: Bluetooth },
  { id: "satellite", label: "Satélite", icon: Satellite },
  { id: "battery", label: "Bateria", icon: Battery },
  { id: "code", label: "Programação", icon: Code },
  { id: "git-branch", label: "Git", icon: GitBranch },
  { id: "webhook", label: "API", icon: Webhook },
  { id: "link", label: "Link", icon: Link },
  { id: "hash", label: "Hashtag", icon: Hash },
  { id: "settings", label: "Configurações", icon: Settings },

  // Viagem & Turismo
  { id: "globe", label: "Viagem", icon: Globe },
  { id: "earth", label: "Mundo", icon: Earth },
  { id: "hotel", label: "Hotel", icon: Hotel },
  { id: "tent", label: "Camping", icon: Tent },
  { id: "luggage", label: "Mala", icon: Luggage },
  { id: "baggage-claim", label: "Esteira de Bagagem", icon: BaggageClaim },
  { id: "backpack", label: "Mochila", icon: Backpack },
  { id: "mountain", label: "Montanha", icon: Mountain },

  // Natureza & Clima
  { id: "sun", label: "Sol", icon: Sun },
  { id: "sunrise", label: "Nascer do Sol", icon: Sunrise },
  { id: "sunset", label: "Pôr do Sol", icon: Sunset },
  { id: "moon", label: "Lua", icon: Moon },
  { id: "cloud", label: "Nuvem", icon: Cloud },
  { id: "cloudy", label: "Nublado", icon: Cloudy },
  { id: "cloud-rain", label: "Chuva", icon: CloudRain },
  { id: "cloud-snow", label: "Neve", icon: CloudSnow },
  { id: "snowflake", label: "Floco de Neve", icon: Snowflake },
  { id: "umbrella", label: "Guarda-chuva", icon: Umbrella },
  { id: "wind", label: "Vento", icon: Wind },
  { id: "tornado", label: "Tornado", icon: Tornado },
  { id: "waves", label: "Ondas", icon: Waves },
  { id: "leaf", label: "Natureza", icon: Leaf },
  { id: "sprout", label: "Broto", icon: Sprout },
  { id: "flower", label: "Flor", icon: Flower },
  { id: "flower-2", label: "Flores", icon: Flower2 },
  { id: "tree-pine", label: "Árvore", icon: TreePine },
  { id: "trees", label: "Floresta", icon: Trees },
  { id: "shell", label: "Concha", icon: Shell },

  // Pessoas & Animais
  { id: "user", label: "Pessoa", icon: User },
  { id: "users", label: "Família", icon: Users },
  { id: "baby", label: "Bebê", icon: Baby },
  { id: "paw-print", label: "Pet", icon: PawPrint },
  { id: "dog", label: "Cachorro", icon: Dog },
  { id: "cat", label: "Gato", icon: Cat },
  { id: "angry", label: "Reclamação", icon: Angry },

  // Vestuário & Acessórios
  { id: "shirt", label: "Roupa", icon: Shirt },
  { id: "watch", label: "Relógio", icon: Watch },
  { id: "glasses", label: "Óculos", icon: Glasses },
  { id: "pocket", label: "Bolso", icon: Pocket },

  // Diversos
  { id: "flag", label: "Meta", icon: Flag },
  { id: "bell", label: "Alerta", icon: Bell },
  { id: "alarm", label: "Alarme", icon: AlarmClock },
  { id: "bookmark", label: "Marcador", icon: Bookmark },
  { id: "pin", label: "Fixado", icon: Pin },
  { id: "flashlight", label: "Lanterna", icon: Flashlight },
  { id: "pipette", label: "Conta-gotas", icon: Pipette },
  { id: "cone", label: "Cone", icon: Cone },
  { id: "panel-top", label: "Painel", icon: PanelTop },
  { id: "plus", label: "Adicionar", icon: Plus },
];

export type IconOption = (typeof iconOptions)[number];

export const resolveIcon = (iconId: string | null) =>
  iconOptions.find((o) => o.id === iconId)?.icon ?? Tag;
