import {
  Activity,
  Apple,
  Archive,
  ArrowDownToLine,
  Baby,
  Banknote,
  BarChart2,
  Battery,
  Beer,
  Bell,
  Bike,
  Bluetooth,
  Bookmark,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  BusFront,
  Calendar,
  Camera,
  Car,
  Carrot,
  ChefHat,
  CircleDollarSign,
  Clipboard,
  Clock,
  Cloud,
  Coffee,
  Coins,
  Cpu,
  CreditCard,
  DollarSign,
  Dumbbell,
  FileText,
  Film,
  Flag,
  Flower2,
  Folder,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  Medal,
  MessageSquare,
  Microscope,
  Monitor,
  Moon,
  Music,
  Navigation,
  Package,
  PartyPopper,
  PawPrint,
  Pencil,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Printer,
  Receipt,
  ReceiptText,
  Repeat,
  Sandwich,
  School,
  Scissors,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Star,
  Stethoscope,
  Store,
  Sun,
  Tablet,
  Tag,
  Tags,
  Train,
  TrendingDown,
  TrendingUp,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Vault,
  Wallet,
  Wifi,
  Wine,
  Wrench,
} from "lucide";

export const iconOptions = [
  // Finanças
  { id: "wallet", label: "Carteira", icon: Wallet },
  { id: "credit-card", label: "Cartão de crédito", icon: CreditCard },
  { id: "dollar-sign", label: "Dinheiro", icon: Banknote },
  { id: "coins", label: "Moedas", icon: Coins },
  { id: "receipt", label: "Recibo", icon: Receipt },
  { id: "receipt-text", label: "Extrato", icon: ReceiptText },
  { id: "piggy-bank", label: "Poupança", icon: PiggyBank },
  { id: "trending-up", label: "Crescimento", icon: TrendingUp },
  { id: "trending-down", label: "Queda", icon: TrendingDown },
  { id: "bar-chart", label: "Gráfico", icon: BarChart2 },
  { id: "percent", label: "Porcentagem", icon: Percent },
  { id: "tag", label: "Tag", icon: Tag },
  { id: "tags", label: "Tags", icon: Tags },
  // Receitas / entradas
  { id: "arrow-down-to-line", label: "Recebimento", icon: ArrowDownToLine },
  { id: "handshake", label: "Contrato", icon: Handshake },
  { id: "landmark", label: "Banco", icon: Landmark },
  { id: "circle-dollar-sign", label: "Salário", icon: CircleDollarSign },
  { id: "repeat", label: "Recorrente", icon: Repeat },
  { id: "vault", label: "Cofre", icon: Vault },
  { id: "dollar-sign-icon", label: "Rendimento", icon: DollarSign },
  // Compras
  { id: "shopping-cart", label: "Mercado", icon: ShoppingCart },
  { id: "shopping-bag", label: "Compras", icon: ShoppingBag },
  { id: "store", label: "Loja", icon: Store },
  { id: "gift", label: "Presente", icon: Gift },
  { id: "package", label: "Pacote", icon: Package },
  // Casa
  { id: "home", label: "Casa", icon: Home },
  { id: "building", label: "Prédio", icon: Building },
  { id: "building2", label: "Condomínio", icon: Building2 },
  { id: "sofa", label: "Móveis", icon: Sofa },
  { id: "lamp", label: "Iluminação", icon: Lamp },
  { id: "lightbulb", label: "Energia", icon: Lightbulb },
  { id: "plug", label: "Eletricidade", icon: Plug },
  { id: "wrench", label: "Manutenção", icon: Wrench },
  { id: "hammer", label: "Reforma", icon: Hammer },
  { id: "key", label: "Aluguel", icon: Key },
  { id: "lock", label: "Segurança", icon: Lock },
  { id: "scissors", label: "Serviços", icon: Scissors },
  // Alimentação
  { id: "utensils", label: "Alimentação", icon: Utensils },
  { id: "utensils-crossed", label: "Restaurante", icon: UtensilsCrossed },
  { id: "coffee", label: "Café", icon: Coffee },
  { id: "pizza", label: "Pizza", icon: Pizza },
  { id: "sandwich", label: "Lanche", icon: Sandwich },
  { id: "chef-hat", label: "Cozinha", icon: ChefHat },
  { id: "apple", label: "Frutas", icon: Apple },
  { id: "carrot", label: "Verduras", icon: Carrot },
  { id: "beer", label: "Cerveja", icon: Beer },
  { id: "wine", label: "Vinho", icon: Wine },
  // Transporte
  { id: "bus", label: "Ônibus", icon: Bus },
  { id: "bus-front", label: "Transporte público", icon: BusFront },
  { id: "car", label: "Carro", icon: Car },
  { id: "bike", label: "Bicicleta", icon: Bike },
  { id: "plane", label: "Avião", icon: Plane },
  { id: "train", label: "Trem", icon: Train },
  { id: "ship", label: "Navio", icon: Ship },
  { id: "truck", label: "Frete", icon: Truck },
  { id: "fuel", label: "Combustível", icon: Fuel },
  { id: "map-pin", label: "Localização", icon: MapPin },
  { id: "navigation", label: "Navegação", icon: Navigation },
  // Saúde
  { id: "heart", label: "Coração", icon: Heart },
  { id: "heart-pulse", label: "Saúde", icon: HeartPulse },
  { id: "activity", label: "Atividade", icon: Activity },
  { id: "stethoscope", label: "Médico", icon: Stethoscope },
  { id: "pill", label: "Remédio", icon: Pill },
  { id: "dumbbell", label: "Academia", icon: Dumbbell },
  // Trabalho
  { id: "briefcase", label: "Trabalho", icon: Briefcase },
  { id: "laptop", label: "Computador", icon: Laptop },
  { id: "monitor", label: "Monitor", icon: Monitor },
  { id: "printer", label: "Impressora", icon: Printer },
  { id: "phone", label: "Telefone", icon: Phone },
  { id: "mail", label: "E-mail", icon: Mail },
  { id: "message-square", label: "Mensagem", icon: MessageSquare },
  { id: "clipboard", label: "Relatório", icon: Clipboard },
  { id: "file-text", label: "Documento", icon: FileText },
  { id: "folder", label: "Pasta", icon: Folder },
  { id: "archive", label: "Arquivo", icon: Archive },
  { id: "calendar", label: "Agenda", icon: Calendar },
  { id: "clock", label: "Horas extras", icon: Clock },
  // Educação
  { id: "book-open", label: "Livro", icon: BookOpen },
  { id: "graduation-cap", label: "Educação", icon: GraduationCap },
  { id: "school", label: "Escola", icon: School },
  { id: "microscope", label: "Ciência", icon: Microscope },
  { id: "pencil", label: "Lápis", icon: Pencil },
  // Lazer & Entretenimento
  { id: "music", label: "Música", icon: Music },
  { id: "headphones", label: "Fones", icon: Headphones },
  { id: "tv", label: "TV / Streaming", icon: Tv },
  { id: "film", label: "Cinema", icon: Film },
  { id: "camera", label: "Fotografia", icon: Camera },
  { id: "gamepad2", label: "Games", icon: Gamepad2 },
  { id: "party-popper", label: "Festa", icon: PartyPopper },
  { id: "star", label: "Destaque", icon: Star },
  { id: "trophy", label: "Conquista", icon: Trophy },
  { id: "medal", label: "Medalha", icon: Medal },
  // Tecnologia
  { id: "smartphone", label: "Celular", icon: Smartphone },
  { id: "tablet", label: "Tablet", icon: Tablet },
  { id: "cpu", label: "Hardware", icon: Cpu },
  { id: "hard-drive", label: "Armazenamento", icon: HardDrive },
  { id: "wifi", label: "Internet", icon: Wifi },
  { id: "bluetooth", label: "Bluetooth", icon: Bluetooth },
  { id: "battery", label: "Bateria", icon: Battery },
  // Natureza
  { id: "sun", label: "Sol", icon: Sun },
  { id: "moon", label: "Lua", icon: Moon },
  { id: "cloud", label: "Nuvem", icon: Cloud },
  { id: "umbrella", label: "Chuva", icon: Umbrella },
  { id: "leaf", label: "Natureza", icon: Leaf },
  { id: "flower2", label: "Flores", icon: Flower2 },
  { id: "tree-pine", label: "Árvore", icon: TreePine },
  // Pessoas & Vida
  { id: "user", label: "Pessoa", icon: User },
  { id: "users", label: "Família", icon: Users },
  { id: "baby", label: "Bebê", icon: Baby },
  { id: "paw-print", label: "Pet", icon: PawPrint },
  // Outros
  { id: "globe", label: "Viagem", icon: Globe },
  { id: "flag", label: "Meta", icon: Flag },
  { id: "bell", label: "Alerta", icon: Bell },
  { id: "bookmark", label: "Marcador", icon: Bookmark },
];

export type IconOption = (typeof iconOptions)[number];

export const resolveIcon = (iconId: string | null) =>
  iconOptions.find((o) => o.id === iconId)?.icon ?? Tag;
